import "~/styles/globals.css";
import Footer from "../_components/Footer";
import Nav from "../_components/Nav";
import { auth } from "~/server/auth";
import { FaUser, FaSignOutAlt } from "react-icons/fa";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";
import Link from "next/link";
import ProfileNavigation from "../_components/ProfileNavigation";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function ProfileLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {


  const session = await auth();

  if (!session) {
    return (
      <div className="flex w-full min-h-[70vh] flex-col items-center justify-center gap-6 p-5 bg-gray-50">
        <div className="bg-white p-10 rounded-lg shadow-md max-w-md w-full text-center">
          <div className="mb-6">
            <FaUser className="mx-auto text-6xl text-gray-300" />
          </div>
          <h1 className="text-3xl font-bold mb-4 text-gray-800">Вы не авторизованы</h1>
          <p className="text-gray-600 mb-6">Войдите в систему, чтобы получить доступ к своему профилю</p>
          <Link
            href="/api/auth/signin" 
            className="inline-block bg-black text-white font-medium py-3 px-6 rounded-md hover:bg-gray-800 transition-colors"
          >
            Войти в аккаунт
          </Link>
        </div>
      </div>
    );
  }





  return (
    <div className="flex w-full flex-col items-center justify-center p-5 bg-gray-50 min-h-[70vh]">
      <div className="max-w-[1366px] w-full">
        <h1 className="text-3xl font-bold mb-8 text-center">Личный кабинет</h1>
        
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          {/* Боковая панель с информацией о пользователе */}
          <div className="md:col-span-1">
            <div className="bg-white rounded-lg shadow-md p-6">
              <div className="flex flex-col items-center mb-6">
                <div className="w-24 h-24 rounded-full bg-gray-200 flex items-center justify-center mb-4">
                  {session.user.image ? (
                    <img 
                      src={session.user.image} 
                      alt={"иконка пользователя"} 
                      className="w-full h-full rounded-full object-cover"
                    />
                  ) : (
                    <FaUser className="text-4xl text-gray-400" />
                  )}
                </div>
                <h2 className="text-xl font-bold text-gray-800">{session?.user.name}</h2>
                <p className="text-gray-500">{session?.user.email}</p>
              </div>
              
              <ProfileNavigation />
              
              <div className="border-t border-gray-200 mt-4 pt-4">
                <Link
                  href="/api/auth/signout"
                  className="flex items-center py-2 px-3 text-red-600 hover:bg-red-50 rounded-md transition-colors"
                >
                  <FaSignOutAlt className="mr-3" /> Выйти из аккаунта
                </Link>
              </div>
            </div>
          </div>
          
          {/* Основной контент */}
          <div className="md:col-span-3">
            {children}
          </div>
        </div>
      </div>
    </div>
  );
}


